// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lyAXEINg896nQ0jWPYe4igdJXNLqO2o',
    appId: '1:922321033413:web:cbd2e973ccc054e4c478ac',
    messagingSenderId: '922321033413',
    projectId: 'speed-limit-notifier',
    authDomain: 'speed-limit-notifier.firebaseapp.com',
    storageBucket: 'speed-limit-notifier.firebasestorage.app',
    measurementId: 'G-64E658DXQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAls-ESXA4pueTOqpHXq4UgQma_4HQPAtk',
    appId: '1:922321033413:android:3c661325668e300fc478ac',
    messagingSenderId: '922321033413',
    projectId: 'speed-limit-notifier',
    storageBucket: 'speed-limit-notifier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnBXRinNIrJVvFnbYwdK7fHxKekyEZLw',
    appId: '1:922321033413:ios:3e647ae635602d89c478ac',
    messagingSenderId: '922321033413',
    projectId: 'speed-limit-notifier',
    storageBucket: 'speed-limit-notifier.firebasestorage.app',
    iosBundleId: 'com.example.speedLimitNotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRnBXRinNIrJVvFnbYwdK7fHxKekyEZLw',
    appId: '1:922321033413:ios:3e647ae635602d89c478ac',
    messagingSenderId: '922321033413',
    projectId: 'speed-limit-notifier',
    storageBucket: 'speed-limit-notifier.firebasestorage.app',
    iosBundleId: 'com.example.speedLimitNotifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_lyAXEINg896nQ0jWPYe4igdJXNLqO2o',
    appId: '1:922321033413:web:b564c7fcb39fd51fc478ac',
    messagingSenderId: '922321033413',
    projectId: 'speed-limit-notifier',
    authDomain: 'speed-limit-notifier.firebaseapp.com',
    storageBucket: 'speed-limit-notifier.firebasestorage.app',
    measurementId: 'G-LPQ9PJ6YK2',
  );
}
